version: '3'
services:
  db:
    image: mysql:8.0.19
    container_name: guacamole-db
    command: '--default-authentication-plugin=mysql_native_password'
    env_file: .env
    volumes:
      - $PWD/conf/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - $PWD/data:/var/lib/mysql
    networks:
      - net
  daemon:
    image: guacamole/guacd
    container_name: guacamole-daemon
    depends_on:
      - db
    networks:
      - net
  web:
    image: guacamole/guacamole
    container_name: guacamole-web
    env_file: .env
    depends_on:
      - daemon
    networks:
      - net
    ports:
      - "8080:8080"
  proxy:
    image: nginx:1.17.9-alpine
    container_name: guacamole-proxy
    volumes:
      - $PWD/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - net
    ports:
        - "80:80"
networks:
  net:

