version: '3'
services:
  kong-database:
    image: cassandra:3.11.6
    container_name: kong-database
    restart: unless-stopped
    networks:
      - net
  kong-d:
    depends_on:
      - kong-database
    image: kong:1.5.1
    container_name: kong-d
    command: "kong migrations bootstrap"
    environment:
      KONG_DATABASE: cassandra
      KONG_PG_HOST: kong-database
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
    restart: unless-stopped
    networks:
      - net
  kong:
    depends_on:
      - kong-d
    image: kong:1.5.1
    container_name: kong
    environment:
      KONG_DATABASE: cassandra
      KONG_PG_HOST: kong-database
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    restart: unless-stopped
    networks:
      - net
  konga:
    depends_on:
      - kong
    image: pantsel/konga
    container_name: konga
    links:
      - kong:1.5.1
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - net
networks:
  net:
#konga IP:1337
#kong-connect IP:8001
#kong-gateway IP:8000
#Test API https://reqres.in/